name: shop_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  backdrop: ^0.6.2
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  carousel_pro: ^1.0.0
  carousel_pro_nullsafety: ^1.0.2
  cloud_firestore: ^2.5.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_staggered_grid_view: ^0.4.0
  flutter_swiper: ^1.1.6
  fluttertoast: ^8.0.8
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.7
  image_picker: ^0.8.3+2
  list_tile_switch: ^1.0.0
  ndialog: ^4.1.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  smooth_sort: ^2.0.1
  uuid: ^3.0.4
  wave: ^0.2.0

flutter_icons:
  android: true
  image_path: "lib/assets/icon_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/cart_empty_image.png
    - lib/assets/tecomerce_logo_app.png
    - lib/assets/no-order.svg
    - lib/assets/2019_10_4_11_16_13_944.jpg
    - lib/assets/5348.jpg
    - lib/assets/9beceb082a92006c310a72aa8e2fdfaa.png.webp
    - lib/assets/3965951231583083458.jpg
    - lib/assets/egyptian-rice03.jpg
    - lib/assets/item_L_22592825_31019590.jpg
    - lib/assets/long-turn-juice-001.jpg
    - lib/assets/mowafer-200-1-7.jpg
    - lib/assets/أسعار-الجبن.jpg
    - lib/assets/Illustration-of-Google-icon-on-transparent-background-PNG.png
    - lib/assets/addidas.jpg
    - lib/assets/buy_me_logo.png
    - lib/assets/buy_me_logo2.png
    - lib/assets/buy_me_logo3.png
    - lib/assets/buy_me_logo4.png
    - lib/assets/apple.jpg
    - lib/assets/Huawei.jpg
    - lib/assets/Dell.jpg
    - lib/assets/samsung.jpg
    - lib/assets/nike.jpg
    - lib/assets/h&m.jpg
    - lib/assets/empty-wishlist.png
    - lib/assets/blank-profile-picture-973460_1280-1.png
    - lib/assets/1200px-OOjs_UI_icon_alert-destructive.svg.png
    - lib/assets/default-avatar-photo-placeholder-profile-image-vector-21666260.jpg
    - lib/assets/carousel1.png
    - lib/assets/carousel2.jpeg
    - lib/assets/no_result_found_image.png
    - lib/assets/carousel3.jpg
    - lib/assets/empty-wishlist.png
    - lib/assets/CatBeauty.jpg
    - lib/assets/CatClothes.jpg
    - lib/assets/CatFurniture.jpg
    - lib/assets/CatLaptops.png
    - lib/assets/CatPhones.png
    - lib/assets/CatShoes.jpg
    - lib/assets/CatWatches.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
